### ISSUE TITLE
Error while parsing mzMLs converted from tdf

### ISSUE THREAD

**Issue by Cajac102** [smith-chem-wisc/FlashLFQ#141]
Hey,

When running FlashLFQ with mzMLs that were converted from tdf (with tdf2mzml), I run into errors while reading in the files: 
```
Reading spectra file
Problem opening .mzML file data/dda/mzmls/TP17632AUH_Slot2-29_1_18113.mzML; Invalid URI: The format of the URI could not be determined.
```

The mzML can be parsed by other tools/parsers, and I don't get that error with other mzMLs converted from raw/mgf. Could you help me out here? I can also send you the file if necessary.
I'm using FlashLFQ via docker (v1.2.4, but 1.2.5 and 1.2.6 give similar error messages) on Debian 12. 

Cheers,
Caro

**Comment by trishorts** [comment]
can you share the file and I will see what the problem is

**Comment by Cajac102** [comment]
Here's the download link (3.2GB):
https://drive.google.com/file/d/1ahK0zWZh7X8ABVzxRWmATaPgOJa0I6ho/view?usp=share_link

**Comment by trishorts** [comment]
ok. i found the problem and I was able to make a fix for the problem, but I don't understand the problem.
The problem is the source file location string in two places near the top of the mzml
![image](https://github.com/smith-chem-wisc/FlashLFQ/assets/16841846/d986e1e3-7b46-4691-8565-79a0d79e11ca)

if I replace the string with a file path (that doesn't have to be the actual file path), the file will load.
![image](https://github.com/smith-chem-wisc/FlashLFQ/assets/16841846/7284461e-a194-4729-a72c-19be94878862)

This would work for a temporary fix. But you need a text editor that can open a huge file like Notepad++

I will still need to dig into this to understand and fix it and then get the update into a new release.

**Comment by trishorts** [comment]
as an internal note. we should add MS:1002828 and MS:1002817 and their companion strings to SourceFile GetSourceFile()

![image](https://github.com/smith-chem-wisc/FlashLFQ/assets/16841846/b63fdc1a-df5b-42da-baea-17a88eb5c8c7)

**Comment by trishorts** [comment]
this is the error we get during file read. 
![image](https://github.com/smith-chem-wisc/FlashLFQ/assets/16841846/e61b1e04-12bb-4d1e-88f5-1549177df051)

**Comment by trishorts** [comment]
I created a new issue at the tdf2mzml github
https://github.com/mafreitas/tdf2mzml/issues/23

**Comment by Cajac102** [comment]
Thanks for the extensive answer! Adding a simple "/" at the start of the sourceFile location did indeed fix the issue. I'll leave this issue open
