### ISSUE TITLE
peptide quantification and rop-down quantification

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/FlashLFQ#52]
Hi,

Can the software do integration of the quantification data on the peptide level? 
can I use it for middle and top down quantification? can it use isotopic envelopes of protein - either resolved and non-resolved?

**Comment by trishorts** [comment]
Can you clarify the first question? What do you mean when you say "integration of the quantification data? Rob will be in shortly to provide a better answer. If you mean, can FlashLFQ report integrated peak intensities, then the answer, I believe, is yes. However, we have found that peak heights tend to be better. FlashLFQ does use multiple isotope peaks in multiple charge states for each peptide. That is a major advantage over other softwares and leads to better approximations of the abundance.  We generally use peak heights. 

FlashLFQ should work just fine for middle-down. It will also work in principle for top-down but this is still in development. We do lots of top-down and this is a priority for us. 

So, please answer my question and stay tuned to hear from Rob.

**Comment by Dmorgen** [comment]
Hi,
I meant integration of PSM quant into peptide quant values - I think you've answer that one.
thanks!
David.

**Comment by rmillikin** [comment]
**Can the software do integration of the quantification data on the peptide level?**
Do you mean integrate the peak (i.e., the area under the curve), rather than using the peak height? This is possible by setting the "int" parameter to "true" (--int true).

**can I use it for middle and top down quantification? can it use isotopic envelopes of protein - either resolved and non-resolved?**
We've done a very small, preliminary study for using FlashLFQ for quantification of top-down data. It does work, and FlashLFQ should be able to read TDPortal results natively (I forget if they output as csv, tsv etc; you want to convert it to .tsv format if it's not). We don't advertise this functionality of FlashLFQ because it's not extensively tested (again, very preliminary). You will want to use "--rmm false"; this means the monoisotopic peak is not required to be observed. It's lower on my priority list (automatic normalization, improved match between runs, and improved bottom-up protein quantification are high on my to-do list) because top-down data is typically deconvoluted, which provides intensities, and our preliminary studies show that FlashLFQ generally does not seem to improve much over deconvoluted intensities.

By resolved or non-resolved do you mean the isotopic peaks are resolved? Isotope peak resolution is required by FlashLFQ.

**Comment by Dmorgen** [comment]
@rmillikin thanks for the answer! what I tried to ask if low resolution MS1 (such as for proteins >50kDa), without charge state is OK to use?

**Comment by trishorts** [comment]
rob can also speak to this. Currently we use Thermo Deconvolution 4.0 (commercial solution) and ProMex (free solution) to perform deconvolution and peak intensity determination for MS1 spectra of intact proteins/proteforms (top-down). Our proteins are all below 40kDa, but I guess that would for for larger too.

**Comment by rmillikin** [comment]
I don't completely understand; are the isotopic peaks resolved within an isotopic envelope? If the answer is "no" then FlashLFQ won't work for that type of data.

And what do you mean without charge state? In the mass spec they must have a charge to be observed of course; do you mean how to specify a charge in the identifications file if you don't necessarily know it?

I'm not too familiar with deconvolution of non-isotopically-resolved data, e.g. low-res high-mass. There are software solutions for this, but again, I'm not familiar with them enough to give you a recommendation. ProMex is quite good at deconvolution of isotopically-resolved data, though.

**Comment by Dmorgen** [comment]
@rmillikin 
yes, I meant data w/o isotopic resolution.  thanks for the answer!
