### ISSUE TITLE
format of modifications on the sequence

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/FlashLFQ#54]
Hi,

How do I add modifications (specifically various glycans) to the peptide sequence? by mass? any specific format (square brackets?)

Thanks!
David.

**Comment by trishorts** [comment]
in the G-PTM-D task, some are looked for automatically. you can click on the triangle and open it up to see which are included. 
![image](https://user-images.githubusercontent.com/16841846/40486007-ad49defc-5f25-11e8-8041-44c30a13ce43.png)

**Comment by trishorts** [comment]
That's in metamorpheus. FlashLFQ should be able to read the output and integrate accordingly.  If you have mass spec data from another vendor, then I guess you have to follow the format for modifications that you get using MetaMorpheus.

**Comment by Dmorgen** [comment]
OK, thanks! I'll have a look at how MM writes glycans.

**Comment by rmillikin** [comment]
FlashLFQ does not actually use modifications for anything other than to shift the mass to look for, because as you probably realize, different programs write modifications differently and there are simply too many for me to parse into chemical formulas. In essence, FlashLFQ calculates the isotopic distribution using the base amino acid sequence only, and uses the monoisotopic mass provided in the ID file. Large glycans may throw this system off, because they can change the isotopic distribution dramatically; I have not looked into that problem extensively.

So, in essence, it does not matter what format you put the modification in, only that it remains the same between two identifications of the same type.
