### ISSUE TITLE
Caution messafe in running

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/FlashLFQ#57]
Hi,

> I've recieved the following message - "Caution! PSM with sequence ******** could not be read; a peptide with the same modified sequence but with different monoisotopic mass has already been added

I'm guessing itis the consolidation of PSMs to a single peptide?

Thanks!
David.

**Comment by rmillikin** [comment]
Hi David,

The monoisotopic mass in the identification file should be the theoretical mass including the mass of any modifications, so there should only be one mass per modified sequence. This is required to calculate accurate ppm errors, mainly. If a sequence has more than one mass it can confuse some calculations. So yep it does have to do with consolidating PSMs into peptides.

**Comment by Dmorgen** [comment]
Thanks!
I'm using Byonic, which doesn't provide a calculation of the theoretical mass. do you know of any tool that will do that for a peptide list?

Thanks!
David.

**Comment by trishorts** [comment]
if you took .mzid input, you could get mods in a standard format. I guess there are some data converters to .mzid

**Comment by rmillikin** [comment]
I think even then it would be very difficult because of the nomenclature differences. mzID would help for where the mod is localized to, and how to read the name, etc, but different programs have different names for the same mod. MetaMorpheus and MaxQuant have different names for phosphorylation, for example. This makes interpreting the chemical formula of the mod very difficult, unless the chemical formula is annotated in the mzID.

**Comment by Dmorgen** [comment]
I've back calculated the theoretical masses from the observed mass and ppm. does the mass have to be M+H or M?

Thanks!
David.

**Comment by rmillikin** [comment]
The mass needs to be the neutral peptide mass (M, not M+H)

**Comment by Dmorgen** [comment]
Thanks!
