### ISSUE TITLE
quantification of glycopeptides with multiple peaks

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/FlashLFQ#79]
Hi Guys,

I'm doing quite a bit of glycopeptidomics and we've noticed that there are multiple peaks per ID, most probably due to structural differences in the glycans. can you detect and quantify them separately? 

Cheers,
D.

**Comment by trishorts** [comment]
Rob will comment on this I'm sure. We have some nice updates on the way for metamorpheus that will improve coverage and quantification of glycopeptides. Some of these updates are in a pull request. So, hopefully within a month you'll see something. I'll try to remember to send you an email so you'll have a chance to see it in action.

**Comment by Dmorgen** [comment]
Great, thanks!

**Comment by lonelu** [comment]
Hi D,
Do you mean the same glycopeptide has more than one MS1 features? Can you show me an example?
Thanks,
Lei

**Comment by Dmorgen** [comment]
Here one example - all three peaks have MS2 spectra that correspond to the sample glycopeptide.
![image](https://user-images.githubusercontent.com/35773089/59975221-555d1800-95be-11e9-8d14-b82ba9d69f89.png)

**Comment by rmillikin** [comment]
Some peaks are combined together into one peak in FlashLFQ to avoid noisy, near-baseline peaks from being double-counted, which throws off the intensity measurement for a particular peptide, since FlashLFQ uses peak height instead of area for quantification. The tolerance for combining peaks is 5 min, so every peak with the same modified sequence within 5 min of each other is combined into one. I can make this into a user-editable setting. You can also make a workaround with the current code by making the full sequence of each ID different. For example you could do:

```
Base Sequence: REEQFNTTFR
Full Sequence REEQFN(Glyco)TTFR_1

Base Sequence: REEQFNTTFR
Full Sequence REEQFN(Glyco)TTFR_2
```

Then each of those would be reported separately in the Peaks file (and in the Quantified Peptides file). I know it's a little annoying, but it'll work.

**Comment by rmillikin** [comment]
FYI, I've changed this in the upcoming FlashLFQ version. I've decided to not merge peaks together unless they have the same apex. Should help make this kind of thing easier to interpret, but it will probably report several peaks for peptides that bounce in and out of the limit of detection.
